version: 2

defaults: &defaults
  working_directory: ~/qlik-variable-input
  docker:
    - image: cimg/node:16.19.1
  environment:
    GITHUB_ORG: "qlik-oss"
    GITHUB_REPO: "qsVariable"
    PACKAGE_NAME: "qlik-variable-input"

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/qlik-variable-input
      - run:
          name: Install dependencies
          command: pnpm install
      - run:
          name: Unit tests
          command: pnpm run test:unit
      - run:
          name: Build and package
          command: |
            sudo chmod +x scripts/get-version.sh
            export VERSION=$(scripts/get-version.sh)
            echo "Version: $VERSION"
            pnpm run build:zip
          environment:
            NODE_ENV: production
      - persist_to_workspace:
          root: ~/qlik-variable-input
          paths:
            - dist
      - store_artifacts:
          path: dist
          destination: dist
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/qlik-variable-input
      - run:
          name: Install ghr
          command: |
            sudo chmod +x scripts/install-ghr.sh
            scripts/install-ghr.sh
      - run:
          name: Create GitHub Release
          command: |
            sudo chmod +x scripts/get-version.sh
            export VERSION=$(scripts/get-version.sh)
            echo "Version: $VERSION"
            sudo chmod +x scripts/create-release.sh
            scripts/create-release.sh $GITHUB_ORG $GITHUB_REPO $PACKAGE_NAME $VERSION

workflows:
  version: 2
  master_flow:
    jobs:
      - build:
          filters: # Required since jobs that requires this uses tag-filter
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              # Have to ignore branches to make the tags-filter work
              ignore: /.*/
